server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # Disable to avoid conflicts with manual routes
          lower-case-service-id: true
      routes:
        - id: user-service-custom
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<remaining>.*), /${remaining}
            - name: RequestRateLimiter
              args:
                '[redis-rate-limiter.replenishRate]': 2
                '[redis-rate-limiter.burstCapacity]': 4
                '[redis-rate-limiter.requestedTokens]': 1
        # Product service route (no rate limiting for now)
        - id: product-service-custom
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**
          filters:
            - RewritePath=/product-service/?(?<remaining>.*), /$\{remaining}
        # Auth service without rate limiting for login/signup
        - id: auth-service-no-limit
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/?(?<remaining>.*), /$\{remaining}
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Monitoring Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
    gateway:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    '[org.springframework.cloud.gateway]': DEBUG
    '[org.springframework.cloud.gateway.filter.ratelimit]': DEBUG
    '[org.springframework.cloud.gateway.filter.ratelimit.RedisRateLimiter]': DEBUG
